spring.application.name=crypto-trader

server.port=8080

spring.datasource.url=jdbc:mysql://127.0.0.1:3306/crypto_trader
spring.datasource.username=root
spring.datasource.password=Xe4p+igo4fu
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.open-in-view=false

jwt.refreshSecret=IdnhvRrGS5va4s7OH8pLyuelsuJwNvluWaKtN1XaO/hSvLl05MO9xMkFmRx3g7Oayai+/uHP0JUI7ML9388J/vvf666ThJGt1TZGCouNjtE=
jwt.accessSecret=ehvWbxTyNL5WWIiQioG1fhjukK7HT44fe9c1BVE7Bh7wrm90R5/IERAB3+9y3Uu7G9DNx9rDE9N208dE/31pWNZ1ns8ocVLav2AvcyX1V1I=
jwt.refreshExpireDuration=14d
jwt.accessExpireDuration=15m